external:
  package: "com.ukenoveldiyar.sample.shared"
  name: RecomposeScopeImplExtern
  file:
    name: RecomposeScopeImpl.kt
    declaration:
      - function:
          fqName: androidx.compose.runtime.updateChangedFlags
          parameters: [kotlin.Int]
